### ISSUE TITLE
Add IAM Role Support 

### ISSUE THREAD

**Issue by SaiSharathReddy** [numaproj-contrib/aws-sqs-source-go#11]
Instead of using AWS Access Key and Secret having Support for IAM Role will help to avoid maintenance like rotating secret due to compliance.

Also SQS support resource based policies which help to utilize cross account Access using IAM role to manage access via IAM instead of creating user with access key and secret.

**Comment by vigith** [comment]
You should be able to use annotations to include IAM roles.

**Comment by KeranYang** [comment]
There are 3 approaches for an AWS application to access an SQS queue. 1. The application directly uses IAM user credentials(secret/access key) 2. The application assumes an IAM role, then uses STS to get temporary credentials to access the queue and 3. The SQS queue configures a server-side resource policy to allow access from the application ARN.

In our README.md file, we have documentation on approach 1 but lacking 2 and 3. @shubhamdixit863 , could you look into this?

If 2 and 3 are not supported yet, we should implement them as part of this issue. Acceptance Criteria: By reading README.md, user can easily choose one of the approaches and start accessing SQS queue.

Thanks!
