### ISSUE TITLE
Is it tied to use static AWS_ACCESS_KEY and AWS_SECRET ENV variables only?

### ISSUE THREAD

**Issue by whynowy** [numaproj-contrib/aws-sqs-source-go#7]
According to https://github.com/numaproj-contrib/aws-sqs-source-go/blob/main/main.go#L34-L41

If there's no ENV variables provided, does it still try to use Metadata API to get credentials (this is the approach that those non-credential solutions like KIAM leverage)?

Based on the [doc](https://github.com/aws/aws-sdk-go/blob/main/aws/session/doc.go#L24-L31) from AWS lib, shall we just use `NewSession`?

**Comment by shubhamdixit863** [comment]
fixed the issue in this pr -https://github.com/numaproj-contrib/aws-sqs-source-go/pull/9
